### ISSUE TITLE
[Feature Request] Render Graph from apipost/v1/send_command generated JSON 

### ISSUE THREAD

**Issue by vproHacks** [google-ai-edge/model-explorer#113]
Disclaimer: This may not actually be an issue, currently when I run the following command:
```js
let cmd = {
            "extensionId": "my_adapter",
            "cmdId": "convert",
            "modelPath": model_path,
            "deleteAfterConversion": false,
            "settings": {},
};
```

 using the model_explorer API, the JSON graph that's returned can't be parsed by the builtin JSON adapter. I wonder if there's anything I'm doing wrong or how I would be able to a graph saved in JSON, modify the JSON a bit, and re-render it using the JSON Adapter.

**Comment by jinjingforever** [comment]
Hi @vproHacks 

The response from `send_command` looks like this:

<img width="530" alt="Screenshot 2024-07-31 at 11 50 45 AM" src="https://github.com/user-attachments/assets/577eef73-18e9-477c-bd89-76983a6d4e1e">

What you need to do is to take the first element of `graphCollections` out and save that into a json file:

```json
{
  "label": "",
  "graphs": [
    {
      "id": "main",
      "nodes": []
    }
}
```

Please give it a try! Thanks
