### ISSUE TITLE
Graph with 4900 nodes takes a long time to render

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#140]
It's been like this for many minutes and hasn't rendered yet (netron renders it easily): 
<img width="431" alt="image" src="https://github.com/user-attachments/assets/b3731f3d-3158-42d2-a945-25c0ea312b27">

Graph: 
[big-lama.onnx.json](https://github.com/user-attachments/files/16843180/big-lama.onnx.json)

**Comment by pkgoogle** [comment]
Hi @justinchuby, is this intended to be used w/ your ONNX adapter (i.e. should I remove the .json and use your ONNX adapter) or with the raw adapter?

**Comment by justinchuby** [comment]
It is the json file I saved from the UI so the raw adapter should work? If needed I can provide the ONNX model.

**Comment by pkgoogle** [comment]
Hi @justinchuby, I am able to load/render properly on both Mac and Linux (Debian) with the default adapter and the .json file as is. Can you ensure your package is updated? or let me know what version of the ai-edge-model-explorer package you are using?

**Comment by justinchuby** [comment]
It does work now for some reason! Maybe my computer was slow that day. I was using 0.10. Feel free to mark this as done, thanks for taking a look.
