### ISSUE TITLE
[StableHLO] Failed to layout graph 

### ISSUE THREAD

**Issue by Nullkooland** [google-ai-edge/model-explorer#171]
I tried to visualize a StableHLO model with model-explorer, but got this error:
```
Failed to layout graph: RangeError: Maximum call stack size exceeded
```
Could you take a look of my model IR, I think it is not malformed since it can be processed by `stablehlo-opt` tool with no problem:
[text_encoder_1_77_256.mlir.txt](https://github.com/user-attachments/files/17001828/text_encoder_1_77_256.mlir.txt)

**Comment by pkgoogle** [comment]
I was able to reproduce, but I never reached the maximum call stack (Infinite loop). @yijie-yang, can you please take a look? Thanks.

**Comment by yijie-yang** [comment]
The backend adapter was able to convert the mlir to JSON graph successfully. Looks like there are some minor issues in UI layout rendering. Jing is inspecting.

**Comment by Nullkooland** [comment]
> We found the issue: the default max number of nodes per layer is set to 1000, which can cause rendering issues when graph is huge. Setting to a smaller value will resolve it! ![BAorH6QhFPD9Fg6](https://private-user-images.githubusercontent.com/47220338/367952770-9d43c211-ac11-411d-aa3d-c7bacad87904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjQ5NTgsIm5iZiI6MTcyNjYyNDY1OCwicGF0aCI6Ii80NzIyMDMzOC8zNjc5NTI3NzAtOWQ0M2MyMTEtYWMxMS00MTFkLWFhM2QtYzdiYWNhZDg3OTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAxNTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYWIyMzUyZmYxZmRhNTVkMTUxYjE0ODdjM2NkNDAyNDA5MzU0Zjk0ZDVjMDFhMzc0NTUwMzMzOGU4NTIyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cd2q3d2Bxxfeoi8zC-bG42f13M9laA8K3p_uuBFrcZE)

It works now, thanks!
