### ISSUE TITLE
[Feature Request] Optionally suppress display of node data when it is not available.

### ISSUE THREAD

**Issue by rvijayc** [google-ai-edge/model-explorer#213]
I recently started using this tool and I find it very useful.

In the example below, some node data json files have entries for only a *subset of nodes*, but I don't see an option to prevent the display of node information for nodes that don't have any entries - they still show up as "-" everywhere which is cluttering the display. 

If there is a way to suppress these, please let me know. If not, please consider this a new feature request.

![image](https://github.com/user-attachments/assets/a7489730-7552-4a53-a69e-4af227be15a5)

Appreciate your help!

**Comment by pkgoogle** [comment]
I don't see a way to do this currently. @jinjingforever can you please take a look? Thanks.

**Comment by jinjingforever** [comment]
This will be released next week. Thanks!
