### ISSUE TITLE
There's no linux arm64 wheel

### ISSUE THREAD

**Issue by tf-nv** [google-ai-edge/model-explorer#223]
Looking at the available builds on pypi, there is no linux arm64 build: https://pypi.org/project/ai-edge-model-explorer-adapter/#files

Would it be possible to provide such a build? Or provide build instructions for an installation from source? Thanks!

**Comment by pkgoogle** [comment]
Hi @yijie-yang, can you please take a look? Thanks.

**Comment by yijie-yang** [comment]
Sorry for the late reply, I missed this issue in my backlog. Since there is no public github runners that guarantee to be linux arm64, we'll request for a self-hosted runner for this architecture. Will update it here once supported.

**Comment by justinchuby** [comment]
consider using qemu? https://github.com/onnx/onnx/blob/main/.github/workflows/release_linux_aarch64.yml#L26C39-L26C46

**Comment by tf-nv** [comment]
I just went for a native linux machine in the end
