### ISSUE TITLE
Contribution process

### ISSUE THREAD

**Issue by GeorgeARM** [google-ai-edge/model-explorer#229]
Hello, 

Interested in contributing support over upstream MLIR visualisation.
As there is already tight integration with MLIR in model-explorer, would this be an area that you would be open in accepting contributions in your built-in adapters?

Thank you in advance,
George

**Comment by pkgoogle** [comment]
Hi @yijie-yang, I believe you would know best. Thanks.

**Comment by yijie-yang** [comment]
Hi George,

Thanks for your interest in contributing to this project! While we agree that enhancing MLIR visualization within model explorer would be valuable, our staffs are currently in short of bandwidth for other deliveries. This means that a concrete timeline for opening up contributions to our built-in adapters is indeterminate at this time.

However, we'd love for you to explore our [Python Extension API](https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension) as a potential avenue for your contributions. Our Python server code is open source and welcomes contributions. This could be a great way to integrate your MLIR visualization ideas into model explorer.

We will definitely keep you updated on any changes regarding contributions to built-in adapters. In the meantime, please feel free to explore the Python API and share any feedback or suggestions you may have :)

Best,
Eric

**Comment by GeorgeARM** [comment]
Thank you very much for your response.
Looking forward for any updates on the contribution scope/process.
