### ISSUE TITLE
reuse_server() does not work with pytorch ExportedProgram

### ISSUE THREAD

**Issue by Erik-Lundell** [google-ai-edge/model-explorer#231]
Hi, very nice application! I noticed that the visualize_pytorch() api was missing a reuse_server option, and tried using visualize_from_config() with add_model_from_pytorch as a workaround. This however fails to send the json generated from the ExportedProgram to the server.

It seems like all parts needed to fix this are in place and I was able to do a hacky-fix where I just added a new field "pytorch_json" to the get/set_transferable data functions in the config and modified the '/api/v1/load_graphs_json' route. Maybe you could make or suggest a better solution? Thanks!

**Comment by pkgoogle** [comment]
Hi @Erik-Lundell, go ahead and make a PR -- the review will either accept your suggestion or we will make a less hacky fix. Thanks for your help.

**Comment by jinjingforever** [comment]
@Erik-Lundell Actually I have a fix ready and will merge it soon. Thanks for the report!

**Comment by jinjingforever** [comment]
This will be released next week. Thanks!

**Comment by Erik-Lundell** [comment]
That is great to hear, much appreciated! Thanks
