### ISSUE TITLE
Bug when pinning a node to the top of a layer

### ISSUE THREAD

**Issue by Ha-Eyz** [google-ai-edge/model-explorer#249]
Hi, I ran into a bug, when pinning nodes to the top of a layer. It happens, when the pinned node is the only node in the Layer.

Here is a small example:
  
   
    from typing import Dict

    from model_explorer import (Adapter, AdapterMetadata, ModelExplorerGraphs,
                                    graph_builder)
      
    
    class MyAdapter(Adapter):
    
      metadata = AdapterMetadata(id='my-adapter',
                                 name='My first adapter',
                                 description='My first adapter!',
                                 source_repo='https://github.com/user/my_adapter',
                                 fileExts=['test'])
    
      def __init__(self):
        super().__init__()
    
      def convert(self, model_path: str, settings: Dict) -> ModelExplorerGraphs:
    
        # Create a graph for testing
        graph = graph_builder.Graph(id='testing')
      
        Alpha_1 = graph_builder.GraphNode(id="Alpha_1", label="Alpha", namespace="Top_Node_Alpha_and_Beta")   
        Alpha_1.config = config=graph_builder.GraphNodeConfig(True) 
        
        Beta = graph_builder.GraphNode(id="Beta", label="Beta", namespace="Top_Node_Alpha_and_Beta")
        
        Alpha_2 = graph_builder.GraphNode(id="Alpha_2", label="Alpha", namespace="Alpha")
        
        Alpha_3 = graph_builder.GraphNode(id="Alpha_3", label="Alpha", namespace="Top_Node_Alpha")
        Alpha_3.config = config=graph_builder.GraphNodeConfig(True)
        
        graph.nodes.extend([Alpha_1, Beta, Alpha_2, Alpha_3])
      
        return {'graphs': [graph]}

![grafik](https://github.com/user-attachments/assets/eea3b7bb-095e-4d91-ae67-6f5a0a9694da)

Opening the Top_Node_Alpha layer results in nothing being shown at all.

**Comment by pkgoogle** [comment]
Using the latest package and your code I'm seeing something a little different:

![image](https://github.com/user-attachments/assets/018b7d02-a56d-44e9-bdfd-e5a4e77f2f5a)

It appears the namespace "supernode" is just rendering as just the element... I'm not sure which is expected/proper.

@jinjingforever, can you please take a look? Thanks.

**Comment by jinjingforever** [comment]
Thanks for the report! And thanks @pkgoogle for investigation.

I think @Ha-Eyz might have [this setting](https://github.com/user-attachments/assets/af5ed6d1-3621-41af-b0d4-5f870f2f2f5c) turned on. I can reproduce the issue. I will take a closer look. Thanks!

**Comment by jinjingforever** [comment]
This should be fixed by https://github.com/google-ai-edge/model-explorer/commit/85fc2185f8336137ee925d26dcf963c382954dee and I will release it soon later today. Thanks!
