### ISSUE TITLE
ONNX Support

### ISSUE THREAD

**Issue by ogencoglu** [google-ai-edge/model-explorer#40]
Thanks for the tool. Any plans to support ONNX?

**Comment by yermandy** [comment]
ONNX would be helpful

**Comment by aboubezari** [comment]
My team also mainly uses ONNX to visualize models. Support for this would be great!

**Comment by yijie-yang** [comment]
Yes, we're planning to support ONNX in this June! Stay tuned!

**Comment by justinchuby** [comment]
https://github.com/justinchuby/model-explorer-onnx/

**Comment by justinchuby** [comment]
I created an extension for ONNX. Happy to contribute.

**Comment by justinchuby** [comment]
@maderix could you share a snapshot to show what you mean? If possible sharing the model would be helpful too

**Comment by maderix** [comment]
@justinchuby , sorry I'm an idiot. Had to just flatten the hierarchy to see the missing connection to nodes. Layers were probably messing my graph.
Thanks for the great addition to this repo . Cheers! :)

**Comment by pkgoogle** [comment]
Hi @ogencoglu, it looks like this is done now. Let us know if you have any other open items here. Thanks.

**Comment by pkgoogle** [comment]
Hi @ogencoglu, does the above adapter satisfy your use case? Thanks for your help.

**Comment by ogencoglu** [comment]
I will try out, thanks.
