### ISSUE TITLE
Open-source front end code

### ISSUE THREAD

**Issue by hlvlad** [google-ai-edge/model-explorer#47]
Hello, thank you for great app!
It seems that currently web-app is shipped in bundled form in repository. I see great potential in such graph editor, in particular to explore large CMake build trees. Are there any plans to open source original Javascript/Typescript front end code?

**Comment by JoanLaRosa** [comment]
+1

**Comment by sousoux** [comment]
+1

**Comment by baswelsh** [comment]
+1

**Comment by yonghah** [comment]
+1

**Comment by zhepoch** [comment]
+1

**Comment by pkgoogle** [comment]
Hi @hlvlad, I'll look into this and get back to you.

**Comment by Subashkatel** [comment]
Hey @pkgoogle , I was wondering, when do you plan on opening source this?

**Comment by pkgoogle** [comment]
Hi @Subashkatel, the current plan is on the next release. There's still uncertainty on that time, but I will say it's at least 3 weeks away.

**Comment by zhepoch** [comment]
any updates?

**Comment by nsmithtt** [comment]
+1

**Comment by Subashkatel** [comment]
Hey @pkgoogle any further updates regarding this?

**Comment by pkgoogle** [comment]
Hi All, thank you for your patience. There was a lot of uncertainty around this so I didn't want to communicate anything incorrect w/o some clarity. Currently the expectation is that it is at least 2 months away due to the level of internal only code that we cannot open source. It's effectively a refactor, thanks again.

**Comment by salazarm** [comment]
+1

**Comment by zhepoch** [comment]
Hi gays, I find this repo https://github.com/jinjingforever/me-external-test, seem like is developer want to public front source code created temp repo.

**Comment by jinjingforever** [comment]
Yes, we are actively working on open-sourcing the UI code and will be releasing it this week or next week. Stay tuned! 

(Sorry, had to take my test repo offline for now :) )

**Comment by jinjingforever** [comment]
The front-end code has been open-sourced. See https://github.com/google-ai-edge/model-explorer/tree/main/src/ui

Thanks for the patience!
