### ISSUE TITLE
[Feature Request] Support displaying model/node metadata

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#48]
There are model metadata that is not currently representable in the `Graph` object. It would be great to provide a mechanism to include more metadata.

Would also be great to allow metadata on nodes (from the model).

Also the `NodeDataResult` for custom node data can only be a number at the moment. Supporting strings in some ways would be useful.

**Comment by pkgoogle** [comment]
Hi @justinchuby, thanks for your request. Just a small point of clarification , are you saying metadata is in the model/nodes but it is not being displayed? or that the underlying model object itself is not allowing model metadata?

**Comment by justinchuby** [comment]
The underlying model object itself is not allowing model metadata as I understand. I couldn’t find a field on Graph to add metadata.

**Comment by pkgoogle** [comment]
Hi @justinchuby do you have a model with metadata we can use as an example?

**Comment by justinchuby** [comment]
For example https://github.com/onnx/models/blob/main/Natural_Language_Processing/bert_Opset18_transformers/bert_Opset18.onnx

![image](https://github.com/google-ai-edge/model-explorer/assets/11205048/6960dfce-e566-4198-9124-c1df6dcae2de)

you can find ir_version, producer, version and others (https://github.com/onnx/onnx/blob/88f8ef15cfaa3138d336f3502aed5018d802bf43/onnx/onnx.proto#L357) and https://github.com/onnx/onnx/blob/88f8ef15cfaa3138d336f3502aed5018d802bf43/onnx/onnx.proto#L490 around both the model and the graph.

It would be good enough if there is a metadata field for graphs in model explorer so we can put all of these key-value pairs there.

**Comment by jinjingforever** [comment]
Hi,

We've added the support to add custom metadata to graph in v0.1.10. Please give it a try:

- Add support for adding custom attributes to group/layer nodes.
    Use the new `groupNodeAttributes` field in `graph_builder.Graph`. Example:

    ```python
    graph = gb.Graph(id='graph',
                     nodes=[top_node, node0, node1, node2],
                     groupNodeAttributes={
                         # Use empty name for graph-level attributes.
                         '': {'model attr': 'value'},
                         'layer1': {'layer attr': 'value'}})
    ```
    ![graph node attributes](https://github.com/user-attachments/assets/90b8789d-f5e9-447a-b247-44d7404efdb6)

**Comment by justinchuby** [comment]
Thank you!

**Comment by justinchuby** [comment]
https://github.com/justinchuby/model-explorer-onnx/releases/tag/v0.3.0
