### ISSUE TITLE
[Feature Request] Display equivalent edges

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#54]
Right now it is only possible to highlight all input edges of a node, but there is no way to tell which edges correspond to the same output value:

<img width="1228" alt="image" src="https://github.com/google-ai-edge/model-explorer/assets/11205048/379a3ebd-6308-4224-ac03-3503bafcf596">

**Compared to netron where it is possible to select a single output:**

<img width="673" alt="image" src="https://github.com/google-ai-edge/model-explorer/assets/11205048/c1a12172-8fca-4929-9cc6-a6bc2aa163a6">

**Comment by jinjingforever** [comment]
Thanks for the feedback! We added toggles to all inputs and outputs to allow you to hide highlights:

<img width="368" alt="toggle io visibility" src="https://github.com/google-ai-edge/model-explorer/assets/8752427/17412daa-1ddb-4246-b6db-bd46075d97f7">

**Tips**: Alt+click the "eye" icon to show the highlight for that item and hide the rest.
