### ISSUE TITLE
Values not displayed completely

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#56]
I followed the settings to set the value display limit to `1024`, but the actual values displayed do not match the size of the weights (`arg0_1`): 

<img width="1122" alt="image" src="https://github.com/google-ai-edge/model-explorer/assets/11205048/f2c4bb2e-68ec-478e-936f-3d2a12a6a945">

This is from the quick_start example colab.

**Comment by jinjingforever** [comment]
Thanks for the report! 

Looks like the PyTorch adapter does not take the settings into account properly. We will take a look. 

@yijie-yang we should probably pass the [settings](https://github.com/google-ai-edge/model-explorer/blob/main/src/server/package/src/model_explorer/builtin_pytorch_exportedprogram_adapter.py#L42) into `PytorchExportedProgramAdapterImpl` and use it to control [size_limit](https://github.com/google-ai-edge/model-explorer/blob/main/src/server/package/src/model_explorer/pytorch_exported_program_adater_impl.py#L154C7-L154C19).

**Comment by justinchuby** [comment]
The values attribute is not rendered correctly: spaces are shown as `?`:

![image](https://github.com/google-ai-edge/model-explorer/assets/11205048/07f80442-1619-4f2e-8463-19fe82727c6a)

**Comment by jinjingforever** [comment]
@justinchuby For the '?' in value attribute, could you share the model? Thanks!

**Comment by justinchuby** [comment]
Sure: [gptneox_Opset18.onnx.json](https://github.com/google-ai-edge/model-explorer/files/15381798/gptneox_Opset18.onnx.json)

**Comment by jinjingforever** [comment]
The values display issue should be fixed in v0.1.1. Thank you!
