### ISSUE TITLE
How to Load Huggingface Model into Model Explorer

### ISSUE THREAD

**Issue by ashishpatel26** [google-ai-edge/model-explorer#57]
I am trying to load a Huggingface model into Model Explorer but couldn't find any documentation or examples on how to do this. The README and Wiki primarily cover TFLite, TF, TFJS, MLIR, and PyTorch (Exported Program) formats. Could you provide guidance or add support for Huggingface models?

**Steps to Reproduce:**
1. Install Model Explorer using pip.
2. Attempt to load a Huggingface model.
3. Observe the lack of documentation or support for Huggingface models.

**Expected Behavior:**
Clear instructions or built-in support for loading Huggingface models into Model Explorer.

**Environment:**
- OS: Windows 11
- Model Explorer Version: Latest

**Additional Context:**
AAny pointers or workarounds would be appreciated. Thank you!

**Comment by pkgoogle** [comment]
Hi @ashishpatel26, is there any particular huggingface model you want to try out? Generally speaking huggingface is more of a hub then a format/framework -- which is why there are no specific instructions for it. Most of the models there are either TF or PyTorch in which case you would follow those instructions. Let us know how we can help you further or if there is an example you want to try.

**Comment by sugatoray** [comment]
## Let's try a specific `transformers` model

You will need the following for authentication from the Colab notebook.

```py
# Save your HF Token in colab secrets as "huggingface" and 
# then use the following to load it up.
import os
from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get('huggingface')
```

Load a `phi-1.5` model.

```py
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

torch.set_default_device("cuda")

model_name_or_path = "microsoft/phi-1_5"

model = AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype="auto")
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)

inputs = tokenizer('''def print_prime(n):
   """
   Print all primes between 1 and n
   """''', return_tensors="pt", return_attention_mask=False)

outputs = model.generate(**inputs, max_length=200)
text = tokenizer.batch_decode(outputs)[0]
print(text)
```

@pkgoogle If you show how to visualize the loaded model from HF using the `transformers` library, that would be helpful.

cc: @ashishpatel26

**Comment by sugatoray** [comment]
## Attempt for Using HF Transformers

I tried the following, but it resulted in an error.

cc: @pkgoogle 

```py
# Get mobilnet v2 pytorch model as an example.
model = model.eval()
inputs = (model.model.dummy_inputs.get('input_ids'),)
ep_hf = torch.export.export(model, inputs)

# Visualize
model_explorer.visualize_pytorch(model_name_or_path, exported_program=ep_hf)
```

This ends in the following error:

<details>
<summary>👉 Click to expand</summary>
<p>

```sh
Converting pytorch model to model explorer graphs...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-21-5d679beafa19>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Visualize
----> 8 model_explorer.visualize_pytorch(model_name_or_path, exported_program=ep_hf)

7 frames
[/usr/local/lib/python3.10/dist-packages/model_explorer/apis.py](https://localhost:8080/#) in visualize_pytorch(name, exported_program, host, port, colab_height)
     74   # Construct config.
     75   cur_config = config()
---> 76   cur_config.add_model_from_pytorch(name, exported_program=exported_program)
     77 
     78   # Start server.

[/usr/local/lib/python3.10/dist-packages/model_explorer/config.py](https://localhost:8080/#) in add_model_from_pytorch(self, name, exported_program)
     76     print('Converting pytorch model to model explorer graphs...')
     77     adapter = PytorchExportedProgramAdapterImpl(exported_program)
---> 78     graphs = adapter.convert()
     79     graphs_index = len(self.graphs_list)
     80     self.graphs_list.append(graphs)

[/usr/local/lib/python3.10/dist-packages/model_explorer/pytorch_exported_program_adater_impl.py](https://localhost:8080/#) in convert(self)
    221 
    222   def convert(self) -> ModelExplorerGraphs:
--> 223     return {'graphs': [self.create_graph()]}

[/usr/local/lib/python3.10/dist-packages/model_explorer/pytorch_exported_program_adater_impl.py](https://localhost:8080/#) in create_graph(self)
    217     graph = Graph(id='graph', nodes=[])
    218     for node in self.gm.graph.nodes:
--> 219       graph.nodes.append(self.create_node(node))
    220     return graph
    221 

[/usr/local/lib/python3.10/dist-packages/model_explorer/pytorch_exported_program_adater_impl.py](https://localhost:8080/#) in create_node(self, fx_node)
    210     )
    211     self.add_incoming_edges(fx_node, node)
--> 212     self.add_node_attrs(fx_node, node)
    213     self.add_outputs_metadata(fx_node, node)
    214     return node

[/usr/local/lib/python3.10/dist-packages/model_explorer/pytorch_exported_program_adater_impl.py](https://localhost:8080/#) in add_node_attrs(self, fx_node, node)
    178         node.attrs.append(KeyValue(key='target', value=str(tensor_spec[0])))
    179         node.attrs.append(
--> 180             KeyValue(key='__value', value=self.print_tensor(tensor_spec[1]))
    181         )
    182 

[/usr/local/lib/python3.10/dist-packages/model_explorer/pytorch_exported_program_adater_impl.py](https://localhost:8080/#) in print_tensor(self, tensor, size_limit)
    160       return json.dumps(tensor.detach().numpy().tolist())
    161 
--> 162     return json.dumps((tensor.detach().numpy().flatten())[:size_limit].tolist())
    163 
    164   def add_node_attrs(self, fx_node: torch.fx.node.Node, node: GraphNode):

[/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py](https://localhost:8080/#) in __torch_function__(self, func, types, args, kwargs)
     75         if func in _device_constructors() and kwargs.get('device') is None:
     76             kwargs['device'] = self.device
---> 77         return func(*args, **kwargs)
     78 
     79 # NB: This is directly called from C++ in torch/csrc/Device.cpp
```

</p>
</details>

**Comment by pkgoogle** [comment]
Hi @sugatoray, thanks for the detailed example, I was also able to reproduce here: [gist](https://colab.sandbox.google.com/gist/pkgoogle/33af6955a7a33756ab9933334192932c/model-explorer-57.ipynb) with a T4 GPU kernel. We will take a look.

**Comment by grimaldispizzeria** [comment]
Another adapter of interest would be GGUF format, would a separate issue need be filed for that or is it ok to request here?

**Comment by geraldstanje** [comment]
does the error also exist for a huggingface setfit model?

**Comment by yijie-yang** [comment]
This PR https://github.com/google-ai-edge/model-explorer/pull/63 should fix the issue. We will push a new pypi build this afternoon.

**Comment by yijie-yang** [comment]
> Another adapter of interest would be GGUF format, would a separate issue need be filed for that or is it ok to request here?

Could you file another issue for this adapter request? We have a tight bandwidth for supporting various formats, so this can take some time for development.

We also encourage users to develop their custom adapters by using our [extension API](https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension). We have a section to display our contributors custom adapters here: https://github.com/google-ai-edge/model-explorer?tab=readme-ov-file#community-contributed-adapters.

**Comment by yijie-yang** [comment]
> Hi @sugatoray, thanks for the detailed example, I was also able to reproduce here: [gist](https://colab.sandbox.google.com/gist/pkgoogle/33af6955a7a33756ab9933334192932c/model-explorer-57.ipynb) with a T4 GPU kernel. We will take a look.

I tested this colab with the model on huggingface, it's working now!
<img width="1345" alt="Screenshot 2024-05-30 at 10 45 42 AM" src="https://github.com/google-ai-edge/model-explorer/assets/47220338/25bb7d10-47d3-4640-a0de-86b939165464">

note: the `model name` passed into `model_explorer.visualize_pytorch` currently doesn't support special char `/`, we will push an update to fix it later today.

**Comment by sugatoray** [comment]
@yijie-yang Perfect! Thank you for resolving this swiftly. Can you link the PR if you have not done so already?

**Comment by pkgoogle** [comment]
> @yijie-yang Perfect! Thank you for resolving this swiftly. Can you link the PR if you have not done so already?

Here you go: https://github.com/google-ai-edge/model-explorer/pull/63

**Comment by yijie-yang** [comment]
Closing the issue now.

**Comment by simplew2011** [comment]
```
model = model.eval()
model.config.use_cache = False  # add this line
inputs = (model.model.dummy_inputs.get('input_ids'),)
ep_hf = torch.export.export(model, inputs)
```
