### ISSUE TITLE
[Feature Request] Allow layers with a singular node

### ISSUE THREAD

**Issue by el-agua** [google-ai-edge/model-explorer#68]
Right now, when add the following code:

![image](https://github.com/google-ai-edge/model-explorer/assets/68676272/fd64fdb7-57f2-4cb5-a084-3e91d0097fbb)

I get the following, removing the namespace:

![image](https://github.com/google-ai-edge/model-explorer/assets/68676272/71522283-7da7-4c4b-9c35-9b65be26a75b)

**Comment by jinjingforever** [comment]
Thanks for the feedback! We added a setting to allow you to keep such layers. Thanks!

<img width="680" alt="keep layers with a single op node child" src="https://github.com/google-ai-edge/model-explorer/assets/8752427/306d86ba-11d4-43eb-97a5-cfdaa3cee0f9">
