### ISSUE TITLE
Failed to parse stablehlo program

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#70]
Testing with mlir files: https://github.com/openxla/stablehlo/blob/main/stablehlo/tests/interpret/collective_broadcast.mlir

Resulting in `RuntimeError: INTERNAL: Unable to parse module`

**Comment by yijie-yang** [comment]
It's failed at this step: https://github.com/google-ai-edge/model-explorer/blob/main/src/builtin-adapter/model_json_graph_convert.cc#L362

Could you help take a look at this issue here? @jpienaar

**Comment by jpienaar** [comment]
Hey, this looks like a mismatch in the textual format. StableHLO doesn't guarantee compatibility there. One of the ops may have changed and needs updating the file

**Comment by Sameeranjoshi** [comment]
Can I be able to generate MLIR based graphs using this tool? How complete is the support currently?

**Comment by pkgoogle** [comment]
Hi @Sameeranjoshi, we currently do not support general MLIR. We do generally support StableHLO. Which is why this is an issue. Thanks.
