### ISSUE TITLE
Adding Additional Information per Layer in Side Panel - (along with Node info, attributes, inputs and outputs need to add 5th drop down sub field)

### ISSUE THREAD

**Issue by tsantosh1098** [google-ai-edge/model-explorer#80]
Hello,

I am working on a specific use case to analyze the model's performance. As part of this, I am considering adding a subsection in the side panel to display additional information per layer.

I have a few questions regarding this enhancement:

* Is it possible to add this feature with the current code base of the Model Explorer?
* I am relatively new to front-end development, but I was able to navigate the backend and add new fields in the graph builder. However, I am unsure if these changes will be supported in the frontend.
* Could anyone please provide guidance on how to proceed with this implementation or any documentation that might help me understand how to integrate backend changes with the frontend?

Thank you

**Comment by pkgoogle** [comment]
Hi @tsantosh1098, you are correct, I don't think you can implement this on your own w/o the front-end code -- which we are working on opensourcing: https://github.com/google-ai-edge/model-explorer/issues/47

**Comment by tsantosh1098** [comment]
Thanks for the reply
