### ISSUE TITLE
Rebuild the Model explorer backend - To get the full weights values

### ISSUE THREAD

**Issue by tsantosh1098** [google-ai-edge/model-explorer#82]
I am trying to modify the **ConvertFlatbufferDirectlyToJson()** part of the **direct_flatbuffer_to_json_graph_convert.cc** file.

To re-build the builtin adaptors I followed these steps - https://github.com/google-ai-edge/model-explorer/tree/main/src/builtin-adapter. But after generating the .so file now I am not able to load the extension module ".builtin_tflite_mlir_adapter". 

! Failed to load extension module ".builtin_tflite_mlir_adapter":
/home/armnn/Documents/mcw/model_explorer/lib/python3.12/site-packages/ai_edge_model_explorer_adapter/_pywrap_convert_wrapper.so: undefined symbol: 
_ZN10tensorflow11CSRMatMulOpIN5Eigen16ThreadPoolDeviceEfEC2EPNS_20OpKernelConstructionE 

When I check the path of the .so file, its present in the provided directory.

Currently, I am building this on **ubuntu 24** machine - with Bazel 6.5.0, on Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz

![Screenshot from 2024-06-11 14-01-39](https://github.com/google-ai-edge/model-explorer/assets/40501382/d8369fcf-9eae-40ab-8ba7-dca717ba7407)

**Comment by tsantosh1098** [comment]
so i built for ai_edge_model_explorer_adapter 0.1.0

I have ai_edge_model_explorer_adapter 0.1.0 which is installed using internet downloaded .whl file
The another ai_edge_model_explorer_adapter 0.1.0 is generated by the local built .whl file
So after i inspected the symbols in both shared libraries here is the difference.
Note: The first one is working, second one (local built is not working)

Is this problem bcz of the glic version ?

![Screenshot from 2024-06-11 14-56-53](https://github.com/google-ai-edge/model-explorer/assets/40501382/a138c1f7-4cd2-45bf-8356-91c947686199)

**Comment by pkgoogle** [comment]
Hi @tsantosh1098, can you share the modifications to
> ConvertFlatbufferDirectlyToJson() part of the direct_flatbuffer_to_json_graph_convert.cc

So that we may match your changes and test this out? Thanks for your help.

**Comment by pkgoogle** [comment]
Hi @tsantosh1098, are you sure you need your changes? Have you tried adjusting the maximum element count for constant tensor values:

![image](https://github.com/google-ai-edge/model-explorer/assets/132095473/ce471d3b-57dd-49a1-a0da-23fca9b8a649)

If you enter a -1 here, it will allow you to see unlimited tensor values. Let me know if you have any more questions.

**Comment by pkgoogle** [comment]
Hi @tsantosh1098, just to be clear the UI solution also works right? (We'll need to add it to the wiki so I wanted to verify :) ). Also if you have no more open items regarding this issue, please feel free to close as completed, thanks!
