### ISSUE TITLE
[Feature Request] API Calls like visualize_from_config can't process extensions.

### ISSUE THREAD

**Issue by vproHacks** [google-ai-edge/model-explorer#84]
API Calls can be seen in `src/server/package/src/model_explorer/apis.py`, I'd assume a simple modification like adding the extensions keyword argument as seen in `cmdline.py` of the same parent directory would suffice.

**Comment by pkgoogle** [comment]
Hi @vproHacks, we reviewed your PR and request -- There are probably additional changes needed, we would like to understand your use case better (why you want to make this change) in order for us to help guide you better.

**Comment by vproHacks** [comment]
Hey! I simply wanted to configure the model_explorer using the inbuilt `model_explorer.config()` tool. I couldn't find that there wasn't any way to run a python function to load up this configuration and add my own extension on top of it without having to initiate a subprocess call. I thought that this would be a clean addition on top of the `visualize_from_config` function to provide that functionality. So far this small change has worked with the following script I've set up:

```py
model_explorer.visualize_from_config(
        config=model_explorer_config,
        no_open_in_browser=True,
        port=model_explorer_port,
        extensions=['my_adapter']
    )
```

**Comment by pkgoogle** [comment]
Hi @vproHacks, we are working on unit tests to be able to provide a harness to test out your changes. Thanks for your patience.

**Comment by hamadilubinga** [comment]
Tourmaline noire pierre magique c'est pour la protection.
![20240316_220606](https://github.com/google-ai-edge/model-explorer/assets/157194798/3746e9ca-c6fb-4b28-8ce9-97fcb7b607ab)

**Comment by hamadilubinga** [comment]
![20240316_220606](https://github.com/google-ai-edge/model-explorer/assets/157194798/01192aaa-cceb-4302-a5d6-acd2474b1db3)

**Comment by vproHacks** [comment]
@yijie-yang @pkgoogle Any updates? It's been a while, just hoping that this doesn't get lost.

**Comment by yijie-yang** [comment]
Yes, thanks! We'll add more unit tests to the python package for the code health later. For this PR, it's simple and we can directly approve it.
