### ISSUE TITLE
[Feature Request] Display multiline metadata

### ISSUE THREAD

**Issue by justinchuby** [google-ai-edge/model-explorer#86]
I am able to include a stacktrace information as an attribute field. It would be better if the newlines are displayed.

<img width="367" alt="image" src="https://github.com/google-ai-edge/model-explorer/assets/11205048/7256b7c6-818d-4ef1-b705-5446f8d7ff0a">

**Comment by pkgoogle** [comment]
Hi @justinchuby, thanks for informing us about this. We will work on this for the next release.

**Comment by jinjingforever** [comment]
Hi @justinchuby 

I think the new release also fixes this issue. Now the attribute should correctly display values with `\n` in it. 

For example, the following code

```python
node0 = gb.GraphNode(id='node0', label='node0', namespace='layer1', attrs=[
                     gb.KeyValue(key='attr', value='line 1\nline 2\nline 3')])
```

should show the following (when you expand the value)

![image](https://github.com/user-attachments/assets/a563731a-35c5-4ca4-9571-106d19955a64)

Thanks!
