### ISSUE TITLE
Possible to support any arbitrary DSL based graph generation?

### ISSUE THREAD

**Issue by Sameeranjoshi** [google-ai-edge/model-explorer#90]
I have a Domain Specific Language, the language has dataflow constructs in it and is made for dataflow programming and dataflow hardwares and I want to understand if it's possible to add support in this tool for the language so that I can visualize those dataflow graphs? If so, is there a sample documentation or some commits which did it in the past?

**Comment by justinchuby** [comment]
https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension

**Comment by pkgoogle** [comment]
Hi @Sameeranjoshi, as justinchuby linked -- you can definitely do that and the resource he linked is the right resource to go to. Let us know if you run into any issue regarding following those instructions.
